
const messages = [
    "You are capable of amazing things.",
    "Today is a new beginning.",
    "The future is bright.",
    "Believe in the power of positivity.",
    "You are stronger than you think.",
    "Embrace the journey, not just the destination.",
    "Every day is a second chance.",
    "Your potential is limitless.",
    "Dream big, work hard.",
    "Stay focused and never give up.",
    "Happiness is a choice.",
    "Keep pushing forward.",
    "Small steps lead to big changes.",
    "You are enough just as you are.",
    "Great things take time.",
    "Trust the process.",
    "You are a work in progress, and that's okay.",
    "Failure is the stepping stone to success.",
    "Be kind to yourself.",
    "Your best is yet to come.",
    "Stay positive, work hard, make it happen.",
    "Believe in the magic of the moment.",
    "You are your only limit.",
    "Take the risk or lose the chance.",
    "Don't wait for opportunity, create it.",
    "You can and you will.",
    "Success is a journey, not a destination.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "You are capable of more than you know.",
    "The best view comes after the hardest climb.",
    "Don't stop until you're proud.",
    "Your attitude determines your direction.",
    "The only time you should look back is to see how far you've come.",
    "Keep going, you're getting there.",
    "You are the artist of your own life.",
    "Life is tough, but so are you.",
    "Believe in yourself and all that you are.",
    "Your vibe attracts your tribe.",
    "Focus on the good.",
    "Do something today that your future self will thank you for.",
    "You are more than enough.",
    "Perseverance is the key to success.",
    "Turn your wounds into wisdom.",
    "Doubt kills more dreams than failure ever will.",
    "Good things take time.",
    "Your journey is unique. Embrace it.",
    "Let your dreams be bigger than your fears.",
    "The best is yet to come.",
    "Make today count."
];

document.getElementById("generate").addEventListener("click", () => { 
    const randomMessage = '"' + messages[Math.floor(Math.random() * messages.length)]+ '"';
    document.getElementById('message').textContent = randomMessage;
});